# Generated by Django 3.1.3 on 2023-02-09 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='uptest',
        ),
    ]
