# Generated by Django 3.1.3 on 2023-02-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lastup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taintain',
            name='maintain',
            field=models.IntegerField(),
        ),
    ]
